"""
tsuuid.dimensions_768 — Extension to 768 named semantic axes

The existing 81 axes (in dimensions.py) cover meta/structural semantics:
protocol, hardware, organization, application, entity, field. They give
us trits 1-81.

To ground 768-trit substrate vectors in human-named axes (so Opus can
emit consistent trit patterns per concept across calls), we extend to
768 axes covering semantic territory the meta layers don't touch:
linguistic, cognitive, affective, social, spatial, temporal-fine,
quantitative, logical, aesthetic, physical-domain, abstract-domain,
cultural, action/causal.

Per Dennis 2026-04-27: this is the grounding step before extrapolation.
Without 768 named axes, "Opus generates 768 trits per concept" is just
hallucinating numbers. With them, each trit is anchored in a human-
readable question Opus can answer consistently.

Each axis has:
  - id (1-768)
  - name (snake_case, terse)
  - negative pole (single word/short phrase)
  - neutral
  - positive pole (single word/short phrase)
  - layer (semantic grouping)
"""

from typing import Dict, List

from tsuuid.dimensions import (
    Axis,
    ALL_AXES as _BASE_81,
    AXES_BY_LAYER as _BASE_LAYERS,
)

# ============================================================
# LINGUISTIC LAYER (trits 82-141, 60 axes)
# Grammatical, lexical, and discourse properties.
# ============================================================
LINGUISTIC_AXES = [
    Axis(82,  "tense",              "past",          "tenseless",     "future",         "linguistic"),
    Axis(83,  "aspect",             "perfective",    "neutral_aspect","progressive",    "linguistic"),
    Axis(84,  "voice",              "passive",       "middle",        "active",         "linguistic"),
    Axis(85,  "mood",                "indicative",   "conditional",   "imperative",     "linguistic"),
    Axis(86,  "polarity_grammar",   "negative",      "neutral",       "affirmative",    "linguistic"),
    Axis(87,  "register",           "informal",      "neutral",       "formal",         "linguistic"),
    Axis(88,  "dialect_class",      "vernacular",    "standard",      "literary",       "linguistic"),
    Axis(89,  "lex_class",          "function",      "mixed_class",   "content",        "linguistic"),
    Axis(90,  "lex_specificity",    "vague",         "general",       "specific",       "linguistic"),
    Axis(91,  "lex_concreteness",   "abstract_word", "mixed_concrete","concrete_word",  "linguistic"),
    Axis(92,  "syntactic_complexity","simple",       "moderate_syn",  "complex_syn",    "linguistic"),
    Axis(93,  "discourse_role",     "topic",         "transitional",  "comment",        "linguistic"),
    Axis(94,  "rhetorical",         "narrative",     "descriptive",   "argumentative",  "linguistic"),
    Axis(95,  "speech_act",         "constative",    "phatic",        "performative",   "linguistic"),
    Axis(96,  "deixis",             "distal",        "neutral_deixis","proximal",       "linguistic"),
    Axis(97,  "anaphora",           "cataphoric",    "no_reference",  "anaphoric",      "linguistic"),
    Axis(98,  "definiteness",       "indefinite",    "generic",       "definite",       "linguistic"),
    Axis(99,  "modal_certainty",    "epistemic_low", "epistemic_mid", "epistemic_high", "linguistic"),
    Axis(100, "modal_obligation",   "permission",    "neutral_modal", "necessity",      "linguistic"),
    Axis(101, "evidentiality",      "hearsay",       "inferential",   "direct_witness", "linguistic"),
    Axis(102, "negation_scope",     "wide_scope",    "ambiguous_neg", "narrow_scope",   "linguistic"),
    Axis(103, "quantifier",         "existential",   "ordinary",      "universal",      "linguistic"),
    Axis(104, "comparison_word",    "comparative",   "positive_form", "superlative",    "linguistic"),
    Axis(105, "agent_focus",        "patient_focus", "neutral_focus", "agent_focus",    "linguistic"),
    Axis(106, "subj_object",        "object_topic",  "neutral_topic", "subject_topic",  "linguistic"),
    Axis(107, "given_new",          "given",         "topical",       "new_info",       "linguistic"),
    Axis(108, "irony",              "literal",       "ambiguous_iro", "ironic",         "linguistic"),
    Axis(109, "metaphor",           "literal",       "mixed_meta",    "metaphorical",   "linguistic"),
    Axis(110, "idiom",              "compositional", "fixed_phrase",  "idiomatic",      "linguistic"),
    Axis(111, "code_switch",        "monolingual",   "borrowed",      "code_switched",  "linguistic"),
    Axis(112, "honorific",          "casual",        "neutral_hon",   "honorific",      "linguistic"),
    Axis(113, "vocative",           "non_address",   "indirect_addr", "direct_address", "linguistic"),
    Axis(114, "interrogative",      "declarative",   "exclamative",   "interrogative",  "linguistic"),
    Axis(115, "subjunctive",        "factive",       "neutral_subj",  "counterfactual", "linguistic"),
    Axis(116, "transitivity",       "intransitive",  "ditransitive",  "transitive",     "linguistic"),
    Axis(117, "reflexivity",        "non_reflexive", "neutral_refl",  "reflexive",      "linguistic"),
    Axis(118, "reciprocity",        "asymmetric",    "neutral_recip", "reciprocal",     "linguistic"),
    Axis(119, "ergativity",         "accusative",    "split",         "ergative",       "linguistic"),
    Axis(120, "alignment",          "nominative",    "neutral_align", "absolutive",     "linguistic"),
    Axis(121, "phrase_type",        "verb_phrase",   "mixed_phrase",  "noun_phrase",    "linguistic"),
    Axis(122, "morpheme_density",   "isolating",     "agglutinative", "fusional",       "linguistic"),
    Axis(123, "head_position",      "head_final",    "mixed_head",    "head_initial",   "linguistic"),
    Axis(124, "branching",          "left_branch",   "balanced",      "right_branch",   "linguistic"),
    Axis(125, "argument_structure", "unaccusative",  "ergative_arg",  "unergative",     "linguistic"),
    Axis(126, "telicity",           "atelic",        "ambiguous_tel", "telic",          "linguistic"),
    Axis(127, "boundedness",        "unbounded",     "ambiguous_bnd", "bounded",        "linguistic"),
    Axis(128, "iterativity",        "semelfactive",  "habitual",      "iterative",      "linguistic"),
    Axis(129, "duration_lex",       "punctual_lex",  "moderate_lex",  "durative_lex",   "linguistic"),
    Axis(130, "stativity",          "stative",       "achievement",   "dynamic",        "linguistic"),
    Axis(131, "factivity",          "non_factive",   "neutral_fact",  "factive_pred",   "linguistic"),
    Axis(132, "presupposition",     "asserted",      "implicated",    "presupposed",    "linguistic"),
    Axis(133, "implicature",        "explicit",      "conventional",  "conversational", "linguistic"),
    Axis(134, "pragmatic_force",    "weak_force",    "neutral_force", "strong_force",   "linguistic"),
    Axis(135, "topic_continuity",   "topic_shift",   "topic_pers",    "topic_continued","linguistic"),
    Axis(136, "thematic_role",      "experiencer",   "instrument",    "agent_role",     "linguistic"),
    Axis(137, "case_role",          "oblique",       "core_arg",      "nominative_role","linguistic"),
    Axis(138, "anaphor_distance",   "long_anaphor",  "moderate_dist", "short_anaphor",  "linguistic"),
    Axis(139, "lexical_density",    "function_heavy","mixed_density", "content_heavy",  "linguistic"),
    Axis(140, "elaboration",        "minimal_elab",  "moderate_elab", "elaborated",     "linguistic"),
    Axis(141, "repair_marker",      "fluent",        "filled_pause",  "self_repair",    "linguistic"),
]

# ============================================================
# COGNITIVE / EPISTEMIC LAYER (trits 142-201, 60 axes)
# Belief, knowledge, reasoning, mental states.
# ============================================================
COGNITIVE_AXES = [
    Axis(142, "belief_strength",    "doubt",         "agnostic",      "conviction",     "cognitive"),
    Axis(143, "knowledge_source",   "testimony",     "inference",     "perception",     "cognitive"),
    Axis(144, "knowledge_kind",     "procedural",    "tacit",         "declarative",    "cognitive"),
    Axis(145, "reasoning_type",     "inductive",     "abductive",     "deductive",      "cognitive"),
    Axis(146, "logic_form",         "analogical",    "heuristic",     "formal_logic",   "cognitive"),
    Axis(147, "thought_mode",       "intuitive",     "deliberative",  "analytical",     "cognitive"),
    Axis(148, "attention_focus",    "diffuse",       "moderate_attn", "focused",        "cognitive"),
    Axis(149, "memory_type",        "episodic",      "semantic_mem",  "procedural_mem", "cognitive"),
    Axis(150, "memory_age",         "remote_mem",    "recent_mem",    "working_mem",    "cognitive"),
    Axis(151, "metacognition",      "unaware",       "monitoring",    "regulating",     "cognitive"),
    Axis(152, "introspection",      "external_focus","mixed_intro",   "introspective",  "cognitive"),
    Axis(153, "imagination",        "literal_mind",  "moderate_imag", "imaginative",    "cognitive"),
    Axis(154, "abstraction_level",  "concrete_thought","mixed_abst",  "abstract_thought","cognitive"),
    Axis(155, "creativity",         "convergent",    "moderate_creat","divergent",      "cognitive"),
    Axis(156, "novelty_seek",       "familiar_seek", "balanced_nov",  "novelty_seek",   "cognitive"),
    Axis(157, "uncertainty_tolerance","intolerant", "moderate_unc",  "tolerant",       "cognitive"),
    Axis(158, "decision_style",     "reactive",      "satisficing",   "optimizing",     "cognitive"),
    Axis(159, "risk_attitude",      "averse",        "neutral_risk",  "seeking",        "cognitive"),
    Axis(160, "time_orientation",   "past_oriented", "present_orient","future_oriented","cognitive"),
    Axis(161, "locus_control",      "external_locus","mixed_locus",   "internal_locus", "cognitive"),
    Axis(162, "self_efficacy",      "low_efficacy",  "moderate_eff",  "high_efficacy",  "cognitive"),
    Axis(163, "growth_mindset",     "fixed_mindset", "neutral_mind",  "growth_mindset", "cognitive"),
    Axis(164, "perspective_taking", "egocentric",    "moderate_pers", "decentered",     "cognitive"),
    Axis(165, "theory_of_mind",     "first_order",   "second_order",  "higher_order",   "cognitive"),
    Axis(166, "intent_attribution", "non_intent",    "ambiguous_int", "intentional",    "cognitive"),
    Axis(167, "causal_attribution", "situational",   "interactionist","dispositional",  "cognitive"),
    Axis(168, "fundamental_attr",   "external_attr", "balanced_attr", "internal_attr",  "cognitive"),
    Axis(169, "cognitive_load",     "low_load",      "moderate_load", "high_load",      "cognitive"),
    Axis(170, "bias_anchor",        "low_anchor",    "moderate_anch", "high_anchor",    "cognitive"),
    Axis(171, "bias_confirm",       "disconfirming", "neutral_conf",  "confirming",     "cognitive"),
    Axis(172, "framing_effect",     "loss_frame",    "neutral_frame", "gain_frame",     "cognitive"),
    Axis(173, "availability_bias",  "low_avail",     "moderate_avail","high_avail",     "cognitive"),
    Axis(174, "representativeness", "diagnostic",    "neutral_rep",   "stereotypical",  "cognitive"),
    Axis(175, "hindsight_bias",     "no_hindsight",  "moderate_hind", "hindsight",      "cognitive"),
    Axis(176, "overconfidence",     "underconfident","calibrated",    "overconfident",  "cognitive"),
    Axis(177, "categorization",     "exemplar",      "prototype",     "rule_based",     "cognitive"),
    Axis(178, "mental_model",       "implicit_model","partial_model", "explicit_model", "cognitive"),
    Axis(179, "schema_activation",  "novel",         "moderate_sch",  "schematic",      "cognitive"),
    Axis(180, "expert_novice",      "novice",        "intermediate",  "expert",         "cognitive"),
    Axis(181, "skill_automaticity", "controlled",    "developing",    "automatic",      "cognitive"),
    Axis(182, "transfer_distance",  "near_transfer", "moderate_xfer", "far_transfer",   "cognitive"),
    Axis(183, "encoding_depth",     "shallow_proc",  "moderate_proc", "deep_proc",      "cognitive"),
    Axis(184, "retrieval_ease",     "tip_of_tongue", "moderate_retr", "fluent_retr",    "cognitive"),
    Axis(185, "interference",       "no_interfere",  "moderate_intf", "interference",   "cognitive"),
    Axis(186, "primacy_recency",    "primacy",       "neutral_pos",   "recency",        "cognitive"),
    Axis(187, "illusory_truth",     "skeptical",     "neutral_truth", "credulous",      "cognitive"),
    Axis(188, "dunning_kruger",     "underestimate", "calibrated_dk", "overestimate",   "cognitive"),
    Axis(189, "cog_dissonance",     "consonant",     "ambivalent",    "dissonant",      "cognitive"),
    Axis(190, "satisficing",        "maximizing",    "balanced_sat",  "satisficing",    "cognitive"),
    Axis(191, "fluency_effect",     "disfluent",     "moderate_flu",  "fluent",         "cognitive"),
    Axis(192, "system_thinking",    "system_one",    "mixed_system",  "system_two",     "cognitive"),
    Axis(193, "counterfactual",     "factual",       "weak_counter",  "counterfactual", "cognitive"),
    Axis(194, "mental_simulation",  "no_simulate",   "partial_sim",   "full_simulate",  "cognitive"),
    Axis(195, "abstraction_chain",  "ground_level",  "intermediate",  "highly_abstract","cognitive"),
    Axis(196, "self_reference",     "other_ref",     "mixed_ref",     "self_ref",       "cognitive"),
    Axis(197, "recursion_depth",    "shallow_rec",   "moderate_rec",  "deep_rec",       "cognitive"),
    Axis(198, "ambiguity_sense",    "blind_to_amb",  "neutral_amb",   "ambiguity_aware","cognitive"),
    Axis(199, "intuition_strength", "weak_intuit",   "moderate_int",  "strong_intuit",  "cognitive"),
    Axis(200, "rationality",        "irrational",    "bounded_rat",   "rational",       "cognitive"),
    Axis(201, "wisdom",             "knowledge_only","experienced",   "wise",           "cognitive"),
]

# ============================================================
# AFFECTIVE LAYER (trits 202-261, 60 axes)
# Emotional dimensions, valence-arousal, social emotions.
# ============================================================
AFFECTIVE_AXES = [
    Axis(202, "valence",            "negative_aff",  "neutral_aff",   "positive_aff",   "affective"),
    Axis(203, "arousal",            "calm",          "moderate_aro",  "excited",        "affective"),
    Axis(204, "dominance_aff",      "submissive",    "balanced_dom",  "dominant",       "affective"),
    Axis(205, "joy",                "joyless",       "contented",     "joyful",         "affective"),
    Axis(206, "sadness",            "happy",         "neutral_sad",   "sad",            "affective"),
    Axis(207, "anger",              "calm_anger",    "irritated",     "enraged",        "affective"),
    Axis(208, "fear",               "fearless",      "anxious",       "terrified",      "affective"),
    Axis(209, "disgust",            "appealed",      "neutral_dis",   "disgusted",      "affective"),
    Axis(210, "surprise",           "expected",      "mild_surprise", "shocked",        "affective"),
    Axis(211, "trust",              "distrust",      "neutral_trust", "trust",          "affective"),
    Axis(212, "anticipation",       "dread",         "neutral_ant",   "eager",          "affective"),
    Axis(213, "shame",              "proud",         "neutral_shame", "ashamed",        "affective"),
    Axis(214, "guilt",              "guiltless",     "regret",        "guilty",         "affective"),
    Axis(215, "pride",              "humble",        "neutral_pride", "proud",          "affective"),
    Axis(216, "envy",               "content_envy",  "comparison",    "envious",        "affective"),
    Axis(217, "jealousy",           "secure",        "wary",          "jealous",        "affective"),
    Axis(218, "love",               "indifferent",   "fond",          "loving",         "affective"),
    Axis(219, "hatred",             "loving",        "neutral_hate",  "hateful",        "affective"),
    Axis(220, "compassion",         "indifferent_c", "sympathetic",   "compassionate",  "affective"),
    Axis(221, "empathy",            "alexithymic",   "cognitive_emp", "affective_emp",  "affective"),
    Axis(222, "gratitude",          "ungrateful",    "appreciative",  "grateful",       "affective"),
    Axis(223, "awe",                "mundane_aff",   "appreciative_a","awed",           "affective"),
    Axis(224, "boredom",            "engaged",       "neutral_bore",  "bored",          "affective"),
    Axis(225, "interest",           "disinterested", "moderate_int_a","fascinated",     "affective"),
    Axis(226, "curiosity",          "incurious",     "moderate_cur",  "curious",        "affective"),
    Axis(227, "satisfaction",       "dissatisfied",  "neutral_sat_a", "satisfied",      "affective"),
    Axis(228, "frustration",        "flow",          "obstructed",    "frustrated",     "affective"),
    Axis(229, "hope",               "hopeless",      "uncertain_hope","hopeful",        "affective"),
    Axis(230, "despair",            "hopeful",       "discouraged",   "despairing",     "affective"),
    Axis(231, "loneliness",         "connected",     "neutral_lonely","lonely",         "affective"),
    Axis(232, "belonging",          "outsider",      "associated",    "belonging",      "affective"),
    Axis(233, "embarrassment",      "composed",      "self_conscious","embarrassed",    "affective"),
    Axis(234, "amusement",          "humorless",     "mild_amused",   "amused",         "affective"),
    Axis(235, "contentment",        "discontent",    "neutral_cont",  "content",        "affective"),
    Axis(236, "serenity",           "agitated",      "calm_serene",   "serene",         "affective"),
    Axis(237, "ecstasy",            "subdued",       "joyful_ec",     "ecstatic",       "affective"),
    Axis(238, "melancholy",         "cheerful",      "thoughtful_m",  "melancholic",    "affective"),
    Axis(239, "nostalgia",          "present_focus", "reminiscent",   "nostalgic",      "affective"),
    Axis(240, "wistfulness",        "matter_of_fact","reflective_w",  "wistful",        "affective"),
    Axis(241, "regret",             "no_regret",     "mild_regret",   "deep_regret",    "affective"),
    Axis(242, "remorse",            "callous",       "regretful",     "remorseful",     "affective"),
    Axis(243, "indignation",        "tolerant",      "displeased",    "indignant",      "affective"),
    Axis(244, "outrage",            "tolerant_out",  "annoyed",       "outraged",       "affective"),
    Axis(245, "contempt",           "respectful",    "neutral_contp", "contemptuous",   "affective"),
    Axis(246, "admiration",         "indifferent_ad","appreciative_ad","admiring",      "affective"),
    Axis(247, "reverence",          "irreverent",    "respectful_rev","reverent",       "affective"),
    Axis(248, "schadenfreude",      "sympathetic_s", "neutral_sch",   "schadenfreude",  "affective"),
    Axis(249, "vindication",        "wronged",       "balanced_vind", "vindicated",     "affective"),
    Axis(250, "relief",             "tense_relief",  "easing",        "relieved",       "affective"),
    Axis(251, "anxiety",            "calm_anx",      "uneasy",        "anxious",        "affective"),
    Axis(252, "panic",              "composed_pan",  "flustered",     "panicked",       "affective"),
    Axis(253, "horror",             "indifferent_h", "alarmed",       "horrified",      "affective"),
    Axis(254, "dread",              "anticipating",  "uneasy_dread",  "dreading",       "affective"),
    Axis(255, "elation",            "subdued_el",    "uplifted",      "elated",         "affective"),
    Axis(256, "euphoria",           "subdued_eu",    "happy_eu",      "euphoric",       "affective"),
    Axis(257, "tenderness",         "harsh",         "gentle",        "tender",         "affective"),
    Axis(258, "yearning",           "satisfied_y",   "missing",       "yearning",       "affective"),
    Axis(259, "longing",            "present",       "wishing",       "longing",        "affective"),
    Axis(260, "affection",          "cold_aff",      "warm_aff",      "affectionate",   "affective"),
    Axis(261, "passion",            "indifferent_p", "interested_p",  "passionate",     "affective"),
]

# ============================================================
# SOCIAL / RELATIONAL LAYER (trits 262-321, 60 axes)
# Roles, relationships, hierarchies, social structure.
# ============================================================
SOCIAL_AXES = [
    Axis(262, "kinship",            "stranger",      "acquaintance",  "kin",            "social"),
    Axis(263, "friendship",         "enemy",         "neutral_friend","friend",         "social"),
    Axis(264, "intimacy",           "distant",       "familiar",      "intimate",       "social"),
    Axis(265, "rapport",            "low_rapport",   "moderate_rapp", "high_rapport",   "social"),
    Axis(266, "trust_social",       "betraying",     "tentative",     "trustworthy",    "social"),
    Axis(267, "loyalty",            "treacherous",   "neutral_loyal", "loyal",          "social"),
    Axis(268, "alliance",           "rival",         "neutral_ally",  "ally",           "social"),
    Axis(269, "rivalry",            "cooperative",   "competitive",   "rival_relation", "social"),
    Axis(270, "cooperation",        "competitive_s", "neutral_coop",  "cooperative",    "social"),
    Axis(271, "competition",        "cooperative_c", "neutral_compe", "competitive_r",  "social"),
    Axis(272, "hierarchy_pos",      "subordinate_s", "peer_social",   "superior_s",     "social"),
    Axis(273, "power_relation",     "powerless",     "balanced_power","powerful",       "social"),
    Axis(274, "status_relative",    "low_status",    "equal_status",  "high_status",    "social"),
    Axis(275, "authority_social",   "follower",      "moderate_auth", "leader",         "social"),
    Axis(276, "influence",          "influenced",    "neutral_infl",  "influencer",     "social"),
    Axis(277, "popularity",         "outcast",       "average_pop",   "popular",        "social"),
    Axis(278, "reputation",         "infamous",      "unknown_rep",   "reputable",      "social"),
    Axis(279, "credibility",        "incredible",    "questionable",  "credible",       "social"),
    Axis(280, "respect",            "disrespected",  "neutral_resp",  "respected",      "social"),
    Axis(281, "deference",          "challenging",   "neutral_def",   "deferential",    "social"),
    Axis(282, "obedience",          "defiant",       "compliant_o",   "obedient",       "social"),
    Axis(283, "rebellion",          "compliant_r",   "questioning",   "rebellious",     "social"),
    Axis(284, "conformity",         "deviant",       "individual",    "conformist",     "social"),
    Axis(285, "individuality",      "collective_i",  "balanced_ind",  "individualist",  "social"),
    Axis(286, "collectivism",       "individualist_c","balanced_col", "collectivist",   "social"),
    Axis(287, "in_group",           "out_group",     "neutral_grp",   "in_group",       "social"),
    Axis(288, "tribalism",          "cosmopolitan",  "neutral_trib",  "tribal",         "social"),
    Axis(289, "xenophilia",         "xenophobic",    "neutral_xen",   "xenophilic",     "social"),
    Axis(290, "altruism",           "selfish",       "neutral_alt",   "altruistic",     "social"),
    Axis(291, "selfishness",        "altruistic_s",  "balanced_self", "selfish_r",      "social"),
    Axis(292, "reciprocity_norm",   "exploitative",  "balanced_recip","reciprocal",     "social"),
    Axis(293, "fairness",           "unfair",        "neutral_fair",  "fair",           "social"),
    Axis(294, "justice",            "unjust",        "ambiguous_just","just",           "social"),
    Axis(295, "equality",           "hierarchical_e","graded",        "egalitarian",    "social"),
    Axis(296, "inclusion",          "exclusion",     "neutral_incl",  "inclusion",      "social"),
    Axis(297, "diversity",          "homogeneous",   "mixed_div",     "diverse",        "social"),
    Axis(298, "tolerance",          "intolerant",    "neutral_tol",   "tolerant",       "social"),
    Axis(299, "openness_social",    "closed_social", "selective_s",   "open_social",    "social"),
    Axis(300, "warmth",             "cold_social",   "neutral_warm",  "warm_social",    "social"),
    Axis(301, "competence_perc",    "incompetent",   "average_comp",  "competent",      "social"),
    Axis(302, "morality_perc",      "immoral",       "amoral",        "moral",          "social"),
    Axis(303, "sociality",          "antisocial",    "neutral_soc",   "social_pers",    "social"),
    Axis(304, "extraversion",       "introvert",     "ambivert",      "extravert",      "social"),
    Axis(305, "assertiveness",      "passive_ass",   "balanced_ass",  "assertive",      "social"),
    Axis(306, "aggression",         "passive_agg",   "neutral_agg",   "aggressive",     "social"),
    Axis(307, "dominance_social",   "submissive_s",  "egalitarian_d", "dominant_s",     "social"),
    Axis(308, "submissiveness",     "dominant_sub",  "balanced_sub",  "submissive_r",   "social"),
    Axis(309, "negotiation",        "demanding",     "compromising",  "accommodating",  "social"),
    Axis(310, "conflict_style",     "avoiding",      "compromising_c","confronting",    "social"),
    Axis(311, "communication_style","direct_comm",   "balanced_comm", "indirect_comm",  "social"),
    Axis(312, "self_disclosure",    "guarded",       "selective_disc","open_disc",      "social"),
    Axis(313, "social_distance",    "distant_s",     "moderate_dist_s","close_s",       "social"),
    Axis(314, "boundary",           "permeable",     "moderate_bnd",  "rigid_boundary", "social"),
    Axis(315, "attachment_style",   "avoidant",      "anxious_attach","secure_attach",  "social"),
    Axis(316, "interdependence",    "independent_s", "balanced_inter","interdependent", "social"),
    Axis(317, "social_support",     "isolated_s",    "moderate_supp", "supported",      "social"),
    Axis(318, "obligation_social",  "free_oblig",    "norm_oblig",    "duty_bound",     "social"),
    Axis(319, "social_role",        "informal_role", "ambiguous_role","formal_role",    "social"),
    Axis(320, "transactional",      "relational_t",  "balanced_trans","transactional_r","social"),
    Axis(321, "relational",         "transactional_r","balanced_rel", "relational_r",   "social"),
]

# ============================================================
# SPATIAL LAYER (trits 322-381, 60 axes)
# Position, geometry, orientation, distance.
# ============================================================
SPATIAL_AXES = [
    Axis(322, "vertical_pos",       "below",         "level",         "above",          "spatial"),
    Axis(323, "horizontal_pos",     "left",          "center",        "right",          "spatial"),
    Axis(324, "depth_pos",          "behind",        "alongside",     "front",          "spatial"),
    Axis(325, "interior_exterior",  "outside",       "boundary",      "inside",         "spatial"),
    Axis(326, "north_south",        "south",         "central_lat",   "north",          "spatial"),
    Axis(327, "east_west",          "west",          "central_lon",   "east",           "spatial"),
    Axis(328, "polar_axis",         "equatorial",    "temperate",     "polar",          "spatial"),
    Axis(329, "altitude",           "low_alt",       "mid_alt",       "high_alt",       "spatial"),
    Axis(330, "depth_water",        "shallow",       "moderate_dep",  "deep_water",     "spatial"),
    Axis(331, "distance_phys",      "near",          "medium_dist",   "far",            "spatial"),
    Axis(332, "proximity",          "distant_p",     "moderate_prox", "proximate",      "spatial"),
    Axis(333, "centrality",         "peripheral",    "intermediate_c","central",        "spatial"),
    Axis(334, "containment",        "outside_cont",  "boundary_cont", "inside_cont",    "spatial"),
    Axis(335, "support",            "unsupported",   "supported",     "supporting",     "spatial"),
    Axis(336, "contact",            "separated",     "touching",      "embedded",       "spatial"),
    Axis(337, "occlusion",          "visible",       "partial_occ",   "occluded",       "spatial"),
    Axis(338, "overlap",            "disjoint",      "adjacent",      "overlapping",    "spatial"),
    Axis(339, "alignment_spat",     "misaligned",    "approximate_a", "aligned",        "spatial"),
    Axis(340, "parallelism",        "perpendicular", "oblique",       "parallel",       "spatial"),
    Axis(341, "perpendicular",      "parallel_perp", "oblique_perp",  "perpendicular_r","spatial"),
    Axis(342, "rotation",           "stationary",    "tilted",        "rotating",       "spatial"),
    Axis(343, "orientation_v",      "horizontal_o",  "diagonal",      "vertical_o",     "spatial"),
    Axis(344, "facing_direction",   "facing_away",   "side_facing",   "facing_toward",  "spatial"),
    Axis(345, "symmetry",           "asymmetric_s",  "partial_sym",   "symmetric",      "spatial"),
    Axis(346, "regularity_spat",    "irregular",     "quasi_regular", "regular_spat",   "spatial"),
    Axis(347, "pattern_repeat",     "unique_spat",   "varied",        "repeating",      "spatial"),
    Axis(348, "scale_spatial",      "microscopic",   "human_scale",   "cosmic_scale",   "spatial"),
    Axis(349, "size_relative",      "tiny",          "medium_sz",     "huge",           "spatial"),
    Axis(350, "shape_complexity",   "simple_shape",  "moderate_shp",  "complex_shape",  "spatial"),
    Axis(351, "shape_curvature",    "angular",       "rounded",       "curved",         "spatial"),
    Axis(352, "convexity",          "concave",       "flat",          "convex",         "spatial"),
    Axis(353, "smoothness",         "rough",         "moderate_smth", "smooth",         "spatial"),
    Axis(354, "porosity",           "solid",         "porous",        "hollow",         "spatial"),
    Axis(355, "density_spat",       "sparse_spat",   "moderate_den",  "dense_spat",     "spatial"),
    Axis(356, "connectivity_spat",  "isolated_spat", "linked",        "networked_sp",   "spatial"),
    Axis(357, "clustering",         "dispersed",     "scattered",     "clustered",      "spatial"),
    Axis(358, "boundary_def",       "diffuse_bnd",   "fuzzy_bnd",     "sharp_bnd",      "spatial"),
    Axis(359, "extent",             "compact",       "moderate_ext",  "extended",       "spatial"),
    Axis(360, "elongation",         "round",         "elliptical",    "elongated",      "spatial"),
    Axis(361, "dimensionality",     "linear_dim",    "planar",        "volumetric",     "spatial"),
    Axis(362, "fractality",         "smooth_dim",    "intermediate_f","fractal",        "spatial"),
    Axis(363, "topology_spat",      "simply_conn",   "multiply_conn", "complex_topo",   "spatial"),
    Axis(364, "manifold_curv",      "negative_curv", "flat_curv",     "positive_curv",  "spatial"),
    Axis(365, "geographic_type",    "rural",         "suburban",      "urban",          "spatial"),
    Axis(366, "elevation_terrain",  "valley",        "plain",         "mountain",       "spatial"),
    Axis(367, "wet_dry",            "arid",          "moderate_wet",  "wet_terrain",    "spatial"),
    Axis(368, "ecosystem_spat",     "desert",        "temperate_eco", "tropical",       "spatial"),
    Axis(369, "climate_zone",       "polar_climate", "temperate_cli", "tropical_cli",   "spatial"),
    Axis(370, "settlement",         "wilderness",    "village",       "metropolis",     "spatial"),
    Axis(371, "transit_acc",        "isolated_t",    "accessible_t",  "hub",            "spatial"),
    Axis(372, "border_status",      "interior_b",    "near_border",   "border_region",  "spatial"),
    Axis(373, "open_enclosed",      "enclosed_sp",   "transitional",  "open_sp",        "spatial"),
    Axis(374, "indoor_outdoor",     "outdoor",       "transitional_io","indoor",        "spatial"),
    Axis(375, "natural_built",      "natural_env",   "modified_env",  "built_env",      "spatial"),
    Axis(376, "ground_aerial",      "subterranean",  "ground_level",  "aerial",         "spatial"),
    Axis(377, "fixed_mobile_spat",  "fixed_spat",    "movable",       "mobile_spat",    "spatial"),
    Axis(378, "stable_unstable",    "unstable_spat", "metastable",    "stable_spat",    "spatial"),
    Axis(379, "static_dynamic",     "static_spat",   "quasi_static",  "dynamic_spat",   "spatial"),
    Axis(380, "expanding_contract", "contracting",   "stable_size",   "expanding",      "spatial"),
    Axis(381, "open_closed_topo",   "closed_topo",   "boundary_topo", "open_topo",      "spatial"),
]

# ============================================================
# TEMPORAL-FINE LAYER (trits 382-431, 50 axes)
# Beyond past/present/future: rhythms, durations, sequences.
# ============================================================
TEMPORAL_FINE_AXES = [
    Axis(382, "duration_class",     "instantaneous", "moderate_dur",  "enduring",       "temporal_fine"),
    Axis(383, "frequency_temp",     "rare_temp",     "occasional",    "frequent",       "temporal_fine"),
    Axis(384, "periodicity",        "aperiodic",     "quasi_periodic","periodic",       "temporal_fine"),
    Axis(385, "rhythm",             "arrhythmic",    "syncopated",    "rhythmic",       "temporal_fine"),
    Axis(386, "tempo",              "slow_tempo",    "moderate_tempo","fast_tempo",     "temporal_fine"),
    Axis(387, "acceleration_t",     "decelerating",  "constant_t",    "accelerating",   "temporal_fine"),
    Axis(388, "punctual_extended",  "punctual",      "brief",         "extended_t",     "temporal_fine"),
    Axis(389, "continuous_disc",    "discrete_t",    "intermittent",  "continuous_t",   "temporal_fine"),
    Axis(390, "synchrony",          "asynchronous",  "loosely_sync",  "synchronous",    "temporal_fine"),
    Axis(391, "phase",              "out_of_phase",  "intermediate_p","in_phase",       "temporal_fine"),
    Axis(392, "lag_lead",           "lagging",       "synchronized_l","leading_l",      "temporal_fine"),
    Axis(393, "before_after",       "before_seq",    "concurrent",    "after_seq",      "temporal_fine"),
    Axis(394, "first_last",         "last_seq",      "middle_seq",    "first_seq",      "temporal_fine"),
    Axis(395, "early_late",         "early_t",       "on_time",       "late_t",         "temporal_fine"),
    Axis(396, "ahead_behind",       "behind_sched",  "on_schedule",   "ahead_sched",    "temporal_fine"),
    Axis(397, "deadline_prox",      "overdue",       "approaching_d", "ample_time",     "temporal_fine"),
    Axis(398, "ripeness",           "premature",     "appropriate",   "overripe",       "temporal_fine"),
    Axis(399, "season_pos",         "early_season",  "mid_season",    "late_season",    "temporal_fine"),
    Axis(400, "diurnal",            "night",         "twilight",      "day",            "temporal_fine"),
    Axis(401, "morning_evening",    "evening",       "midday",        "morning",        "temporal_fine"),
    Axis(402, "weekday_weekend",    "weekend",       "intermediate_d","weekday",        "temporal_fine"),
    Axis(403, "monthly_pos",        "month_start",   "month_mid",     "month_end",      "temporal_fine"),
    Axis(404, "yearly_pos",         "year_start",    "year_mid",      "year_end",       "temporal_fine"),
    Axis(405, "decade_era",         "this_decade",   "recent_decade", "distant_decade", "temporal_fine"),
    Axis(406, "century_era",        "this_century",  "recent_century","historical_cent","temporal_fine"),
    Axis(407, "epoch",              "modern",        "industrial",    "ancient",        "temporal_fine"),
    Axis(408, "geological_time",    "present_geo",   "historical_geo","deep_time",      "temporal_fine"),
    Axis(409, "cyclical_linear",    "linear_t",      "spiral_t",      "cyclical_t",     "temporal_fine"),
    Axis(410, "reversible_t",       "irreversible",  "reversible_t",  "fully_reversible","temporal_fine"),
    Axis(411, "transient_lasting",  "transient",     "intermediate_l","lasting",        "temporal_fine"),
    Axis(412, "ephemeral_eternal",  "ephemeral",     "long_lasting",  "eternal",        "temporal_fine"),
    Axis(413, "moment_era",         "moment",        "period",        "era",            "temporal_fine"),
    Axis(414, "interval_uniform",   "irregular_int", "varied_int",    "uniform_int",    "temporal_fine"),
    Axis(415, "burst_steady",       "steady",        "intermittent_b","bursty",         "temporal_fine"),
    Axis(416, "growth_decay_t",     "decaying",      "stable_t",      "growing",        "temporal_fine"),
    Axis(417, "boom_bust",          "bust",          "stable_econ_t", "boom",           "temporal_fine"),
    Axis(418, "wax_wane",           "waning",        "balanced_wax",  "waxing",         "temporal_fine"),
    Axis(419, "rise_fall",          "falling",       "stable_rf",     "rising",         "temporal_fine"),
    Axis(420, "peak_trough",        "trough",        "transition_pt", "peak",           "temporal_fine"),
    Axis(421, "volatility_t",       "volatile",      "moderate_vol_t","stable_t_v",     "temporal_fine"),
    Axis(422, "predictability_t",   "unpredictable", "partially_pred","predictable",    "temporal_fine"),
    Axis(423, "regularity_t",       "irregular_t",   "quasi_regular_t","regular_t",     "temporal_fine"),
    Axis(424, "anniversary",        "non_anniv",     "near_anniv",    "anniversary_t",  "temporal_fine"),
    Axis(425, "milestone",          "ordinary_t",    "minor_mile",    "major_mile",     "temporal_fine"),
    Axis(426, "transition_t",       "stable_pre",    "transitioning", "stable_post",    "temporal_fine"),
    Axis(427, "phase_change",       "before_phase",  "during_phase",  "after_phase",    "temporal_fine"),
    Axis(428, "lifecycle_stage",    "birth",         "maturity",      "death_stage",    "temporal_fine"),
    Axis(429, "novelty_temp",       "established",   "emerging",      "brand_new",      "temporal_fine"),
    Axis(430, "obsolescence",       "current_t",     "aging_t",       "obsolete",       "temporal_fine"),
    Axis(431, "anachronism",        "contemporary",  "out_of_period", "anachronistic",  "temporal_fine"),
]

# ============================================================
# QUANTITATIVE LAYER (trits 432-481, 50 axes)
# Magnitude, units, measurement, statistical properties.
# ============================================================
QUANTITATIVE_AXES = [
    Axis(432, "magnitude_class",    "minute",        "moderate_mag",  "vast",           "quantitative"),
    Axis(433, "order_magnitude",    "low_om",        "mid_om",        "high_om",        "quantitative"),
    Axis(434, "scalar_sign",        "negative_sc",   "zero_sc",       "positive_sc",    "quantitative"),
    Axis(435, "vector_direction",   "negative_vec",  "null_vec",      "positive_vec",   "quantitative"),
    Axis(436, "real_complex",       "real_num",      "real_imag",     "complex_num",    "quantitative"),
    Axis(437, "rational_irr",       "rational",      "approx_real",   "irrational",     "quantitative"),
    Axis(438, "integer_real",       "integer_t",     "rational_q",    "real_q",         "quantitative"),
    Axis(439, "discrete_continuous","discrete_q",    "ordinal_q",     "continuous_q",   "quantitative"),
    Axis(440, "bounded_unbounded",  "bounded_q",     "semi_bounded",  "unbounded_q",    "quantitative"),
    Axis(441, "finite_infinite",    "finite_q",      "very_large",    "infinite_q",     "quantitative"),
    Axis(442, "exact_approx",       "exact_q",       "rounded",       "approximate_q",  "quantitative"),
    Axis(443, "precision_decimal",  "low_prec",      "moderate_prec", "high_prec",      "quantitative"),
    Axis(444, "accuracy_q",         "biased_q",      "moderate_acc",  "accurate_q",     "quantitative"),
    Axis(445, "tolerance_q",        "tight_tol",     "moderate_tol_q","loose_tol",      "quantitative"),
    Axis(446, "uncertainty_q",      "certain_q",     "moderate_unc_q","uncertain_q",    "quantitative"),
    Axis(447, "variance_class",     "constant",      "moderate_var",  "variable",       "quantitative"),
    Axis(448, "dispersion",         "concentrated",  "moderate_disp", "dispersed",      "quantitative"),
    Axis(449, "skewness",           "left_skew",     "symmetric_q",   "right_skew",     "quantitative"),
    Axis(450, "kurtosis",           "platykurtic",   "mesokurtic",    "leptokurtic",    "quantitative"),
    Axis(451, "outlier_status",     "typical_q",     "borderline",    "outlier_q",      "quantitative"),
    Axis(452, "central_tendency",   "below_central", "central_q",     "above_central",  "quantitative"),
    Axis(453, "percentile_band",    "low_pct",       "mid_pct",       "high_pct",       "quantitative"),
    Axis(454, "ratio_unit",         "subunit",       "unit_q",        "multiple",       "quantitative"),
    Axis(455, "proportion",         "minority",      "even_split",    "majority",       "quantitative"),
    Axis(456, "fraction_whole",     "fraction",      "approximate_w", "whole_q",        "quantitative"),
    Axis(457, "log_linear",         "logarithmic",   "polynomial",    "linear_q",       "quantitative"),
    Axis(458, "exponential_q",      "subexponential","linear_e",      "exponential_q",  "quantitative"),
    Axis(459, "power_law",          "uniform_pl",    "normal_pl",     "power_law",      "quantitative"),
    Axis(460, "gaussian_q",         "non_gaussian",  "approx_gauss",  "gaussian",       "quantitative"),
    Axis(461, "stationarity",       "non_stationary","weakly_stat",   "stationary",     "quantitative"),
    Axis(462, "ergodicity",         "non_ergodic",   "quasi_ergodic", "ergodic",        "quantitative"),
    Axis(463, "iid",                "correlated_iid","weakly_iid",    "iid",            "quantitative"),
    Axis(464, "autocorrelation",    "negative_ac",   "uncorrelated",  "positive_ac",    "quantitative"),
    Axis(465, "trend_q",            "decreasing_q",  "flat_q",        "increasing_q",   "quantitative"),
    Axis(466, "seasonality_q",      "non_seasonal",  "weak_seasonal", "seasonal_q",     "quantitative"),
    Axis(467, "noise_signal",       "low_snr",       "moderate_snr",  "high_snr",       "quantitative"),
    Axis(468, "smoothness_q",       "rough_q",       "moderate_smth_q","smooth_q",      "quantitative"),
    Axis(469, "monotonicity",       "decreasing_m",  "non_monotonic", "increasing_m",   "quantitative"),
    Axis(470, "convexity_q",        "concave_q",     "linear_qc",     "convex_q",       "quantitative"),
    Axis(471, "differentiability",  "non_diff",      "weakly_diff",   "smooth_diff",    "quantitative"),
    Axis(472, "integrability",      "non_integrable","weakly_int",    "integrable",     "quantitative"),
    Axis(473, "boundedness_q",      "unbounded_qb",  "weakly_bounded","bounded_qb",     "quantitative"),
    Axis(474, "compactness_q",      "non_compact",   "relatively_c",  "compact_q",      "quantitative"),
    Axis(475, "convergence",        "divergent",     "oscillating",   "convergent",     "quantitative"),
    Axis(476, "limit_behavior",     "no_limit",      "asymptotic",    "exact_limit",    "quantitative"),
    Axis(477, "growth_rate",        "shrinking",     "stagnant",      "growing_q",      "quantitative"),
    Axis(478, "saturation",         "linear_sat",    "approaching",   "saturated",      "quantitative"),
    Axis(479, "threshold_status",   "subthreshold",  "near_threshold","superthreshold", "quantitative"),
    Axis(480, "extreme_event",      "common_q",      "rare_event",    "extreme_event",  "quantitative"),
    Axis(481, "tail_behavior",      "thin_tail",     "moderate_tail", "fat_tail",       "quantitative"),
]

# ============================================================
# LOGICAL LAYER (trits 482-521, 40 axes)
# Logical operators, quantifiers, validity, modal logic.
# ============================================================
LOGICAL_AXES = [
    Axis(482, "truth_value",        "false",         "indeterminate", "true",           "logical"),
    Axis(483, "validity",           "invalid_l",     "weakly_valid",  "valid_l",        "logical"),
    Axis(484, "soundness",          "unsound",       "weakly_sound",  "sound",          "logical"),
    Axis(485, "consistency",        "inconsistent",  "weakly_cons",   "consistent_l",   "logical"),
    Axis(486, "completeness_l",     "incomplete_l",  "partially_comp","complete_l",     "logical"),
    Axis(487, "decidability",       "undecidable",   "semi_decidable","decidable",      "logical"),
    Axis(488, "computability",      "uncomputable",  "complex_comp",  "computable",     "logical"),
    Axis(489, "tractability",       "intractable",   "exponential_t", "polynomial_t",   "logical"),
    Axis(490, "necessity_l",        "contingent_l",  "probable_l",    "necessary_l",    "logical"),
    Axis(491, "possibility_l",      "impossible",    "possible_l",    "actual_l",       "logical"),
    Axis(492, "universality_l",     "particular_l",  "general_l",     "universal_l",    "logical"),
    Axis(493, "existential_l",      "non_existent",  "existential_q", "instantiated",   "logical"),
    Axis(494, "implication",        "anti_implies",  "neutral_imp",   "implies",        "logical"),
    Axis(495, "biconditional",      "asymmetric_b",  "weakly_iff",    "biconditional_b","logical"),
    Axis(496, "contradiction",      "contradicts",   "compatible",    "entails",        "logical"),
    Axis(497, "tautology",          "contingent_t",  "probable_t",    "tautological",   "logical"),
    Axis(498, "consistency_set",    "contradictory", "consistent_set","tautological_s", "logical"),
    Axis(499, "and_or",             "exclusive_or",  "inclusive_or",  "conjunction",    "logical"),
    Axis(500, "negation",           "double_neg",    "neutral_neg",   "negation",       "logical"),
    Axis(501, "quantifier_scope",   "narrow_qs",     "ambiguous_qs",  "wide_qs",        "logical"),
    Axis(502, "monotonicity_l",     "non_monotonic_l","weakly_mono",  "monotonic_l",    "logical"),
    Axis(503, "antecedent",         "consequent",    "biconditional_a","antecedent_l",  "logical"),
    Axis(504, "premise_conclusion", "conclusion",    "lemma",         "premise",        "logical"),
    Axis(505, "axiom_theorem",      "theorem",       "lemma_t",       "axiom",          "logical"),
    Axis(506, "prove_disprove",     "disproved",     "open_l",        "proved",         "logical"),
    Axis(507, "constructive_class", "non_construct", "weakly_const",  "constructive_l", "logical"),
    Axis(508, "classical_intuit",   "intuitionistic","minimal_l",     "classical_l",    "logical"),
    Axis(509, "modal_alethic",      "possible_a",    "actual_a",      "necessary_a",    "logical"),
    Axis(510, "modal_deontic",      "forbidden_d",   "permitted_d",   "obligatory_d",   "logical"),
    Axis(511, "modal_epistemic",    "unknown_e",     "believed",      "known",          "logical"),
    Axis(512, "modal_doxastic",     "disbelieved",   "uncertain_d",   "believed_d",     "logical"),
    Axis(513, "modal_temporal_l",   "always_past",   "sometimes",     "always_future",  "logical"),
    Axis(514, "fuzzy_crisp",        "crisp_l",       "graded",        "fuzzy_l",        "logical"),
    Axis(515, "deterministic_prob", "deterministic_l","ambiguous_dp", "probabilistic",  "logical"),
    Axis(516, "binary_multivalued", "binary_l",      "trivalent",     "multivalued",    "logical"),
    Axis(517, "consistency_inf",    "infinite_inf",  "finite_inf",    "consistent_inf", "logical"),
    Axis(518, "first_higher_order", "propositional", "first_order",   "higher_order_l", "logical"),
    Axis(519, "argument_form",      "fallacious",    "weak_form",     "valid_form",     "logical"),
    Axis(520, "abductive_inductive","inductive_l",   "abductive_l",   "deductive_l",    "logical"),
    Axis(521, "defeasibility",      "defeasible",    "default_l",     "indefeasible",   "logical"),
]

# ============================================================
# AESTHETIC / PERCEPTUAL LAYER (trits 522-571, 50 axes)
# Sensory and aesthetic dimensions.
# ============================================================
AESTHETIC_AXES = [
    Axis(522, "color_warm_cool",    "cool_color",    "neutral_color", "warm_color",     "aesthetic"),
    Axis(523, "color_light_dark",   "dark_color",    "mid_value",     "light_color",    "aesthetic"),
    Axis(524, "color_saturation",   "desaturated",   "moderate_sat",  "saturated_c",    "aesthetic"),
    Axis(525, "color_chromatic",    "achromatic",    "muted_chrom",   "chromatic",      "aesthetic"),
    Axis(526, "brightness",         "dim",           "moderate_br",   "bright",         "aesthetic"),
    Axis(527, "contrast",           "low_contrast",  "moderate_cont", "high_contrast",  "aesthetic"),
    Axis(528, "luminance",          "dark_lum",      "moderate_lum",  "luminous",       "aesthetic"),
    Axis(529, "transparency",       "opaque",        "translucent",   "transparent_a",  "aesthetic"),
    Axis(530, "reflectivity",       "matte",         "satin",         "glossy",         "aesthetic"),
    Axis(531, "texture_smooth",     "rough_tex",     "moderate_tex",  "smooth_tex",     "aesthetic"),
    Axis(532, "texture_density",    "sparse_tex",    "moderate_dens", "dense_tex",      "aesthetic"),
    Axis(533, "pattern_aesth",      "random_pat",    "varied_pat",    "patterned",      "aesthetic"),
    Axis(534, "ornament",           "minimal_orn",   "moderate_orn",  "ornate",         "aesthetic"),
    Axis(535, "harmony_aesth",      "discordant",    "tension_h",     "harmonious",     "aesthetic"),
    Axis(536, "balance_aesth",      "asymmetric_a",  "dynamic_bal",   "balanced_a",     "aesthetic"),
    Axis(537, "proportion",         "disproportion", "varied_prop",   "proportional",   "aesthetic"),
    Axis(538, "rhythm_visual",      "static_v",      "varied_v",      "rhythmic_v",     "aesthetic"),
    Axis(539, "movement_visual",    "still_v",       "implied_motion","moving_v",       "aesthetic"),
    Axis(540, "flow_aesthetic",     "fragmented_f",  "broken_f",      "flowing",        "aesthetic"),
    Axis(541, "unity_aesth",        "fragmented_u",  "loosely_u",     "unified_u",      "aesthetic"),
    Axis(542, "variety_aesth",      "uniform_v",     "moderate_v_a",  "varied_a",       "aesthetic"),
    Axis(543, "emphasis",           "no_emphasis",   "moderate_emph", "emphasized",     "aesthetic"),
    Axis(544, "scale_aesth",        "intimate_s",    "human_s_a",     "monumental",     "aesthetic"),
    Axis(545, "elegance",           "clumsy",        "neutral_elg",   "elegant",        "aesthetic"),
    Axis(546, "beauty",             "ugly",          "neutral_beauty","beautiful",      "aesthetic"),
    Axis(547, "sublime",            "mundane_a",     "impressive",    "sublime_a",      "aesthetic"),
    Axis(548, "kitsch_authentic",   "kitsch",        "stylized",      "authentic_a",    "aesthetic"),
    Axis(549, "minimal_maximal",    "minimal_a",     "moderate_min",  "maximal_a",      "aesthetic"),
    Axis(550, "natural_artificial", "natural_a",     "naturalistic",  "artificial_a",   "aesthetic"),
    Axis(551, "soft_hard_aesth",    "soft_a",        "medium_a",      "hard_a",         "aesthetic"),
    Axis(552, "warm_cold_aesth",    "cold_a",        "neutral_a",     "warm_a",         "aesthetic"),
    Axis(553, "wet_dry_aesth",      "dry_a",         "moist_a",       "wet_a",          "aesthetic"),
    Axis(554, "loud_quiet",         "silent_a",      "moderate_loud", "loud_a",         "aesthetic"),
    Axis(555, "harsh_gentle",       "harsh_a",       "moderate_g",    "gentle_a",       "aesthetic"),
    Axis(556, "sharp_dull",         "dull_a",        "moderate_sh",   "sharp_a",        "aesthetic"),
    Axis(557, "fresh_stale",        "stale_a",       "moderate_f",    "fresh_a",        "aesthetic"),
    Axis(558, "sweet_bitter",       "bitter_a",      "neutral_taste", "sweet_a",        "aesthetic"),
    Axis(559, "savory_bland",       "bland_a",       "moderate_s",    "savory_a",       "aesthetic"),
    Axis(560, "fragrant_acrid",     "acrid_a",       "neutral_smell", "fragrant_a",     "aesthetic"),
    Axis(561, "clean_dirty",        "dirty_a",       "average_clean", "clean_a",        "aesthetic"),
    Axis(562, "polished_raw",       "raw_a",         "rustic_a",      "polished_a",     "aesthetic"),
    Axis(563, "old_new_aesth",      "old_a",         "vintage_a",     "new_a",          "aesthetic"),
    Axis(564, "antique_modern",     "antique_a",     "transitional_a","modern_a",       "aesthetic"),
    Axis(565, "ornamental_funct",   "functional_a",  "balanced_of",   "ornamental_a",   "aesthetic"),
    Axis(566, "sacred_profane",     "profane",       "secular",       "sacred",         "aesthetic"),
    Axis(567, "playful_serious",    "serious_a",     "moderate_play", "playful_a",      "aesthetic"),
    Axis(568, "comic_tragic",       "tragic_a",      "dramatic_a",    "comic_a",        "aesthetic"),
    Axis(569, "earnest_ironic",     "ironic_a",      "ambiguous_e",   "earnest_a",      "aesthetic"),
    Axis(570, "kitsch_camp",        "sincere_k",     "ironic_k",      "camp_a",         "aesthetic"),
    Axis(571, "weighty_light",      "light_a",       "balanced_w",    "weighty_a",      "aesthetic"),
]

# ============================================================
# PHYSICAL LAYER (trits 572-631, 60 axes)
# Matter, energy, biology, chemistry — natural domain content.
# ============================================================
PHYSICAL_AXES = [
    Axis(572, "matter_state",       "solid_st",      "liquid_st",     "gas_st",         "physical"),
    Axis(573, "phase_extreme",      "condensed",     "ordinary_phase","plasma",         "physical"),
    Axis(574, "temperature_class",  "cold_temp",     "ambient",       "hot_temp",       "physical"),
    Axis(575, "thermal_kind",       "endothermic",   "thermo_neutral","exothermic",     "physical"),
    Axis(576, "pressure_class",     "vacuum",        "atmospheric",   "high_pressure",  "physical"),
    Axis(577, "energy_kinetic",     "potential_e",   "balanced_e",    "kinetic_e",      "physical"),
    Axis(578, "energy_form",        "thermal_e",     "chemical_e",    "electromagnetic","physical"),
    Axis(579, "wave_particle",      "particle",      "wave_packet",   "wave",           "physical"),
    Axis(580, "frequency_em",       "low_freq",      "mid_freq",      "high_freq",      "physical"),
    Axis(581, "wavelength",         "short_wl",      "mid_wl",        "long_wl",        "physical"),
    Axis(582, "amplitude",          "small_amp",     "moderate_amp",  "large_amp",      "physical"),
    Axis(583, "polarity_phys",      "unpolarized",   "partially_pol", "polarized",      "physical"),
    Axis(584, "coherence_phys",     "incoherent",    "partially_coh", "coherent",       "physical"),
    Axis(585, "entropy",            "ordered_e",     "intermediate_e","disordered",     "physical"),
    Axis(586, "order_disorder",     "ordered_o",     "intermediate_o","disordered_o",   "physical"),
    Axis(587, "crystalline",        "amorphous",     "polycrystal",   "single_crystal", "physical"),
    Axis(588, "purity",             "impure",        "moderate_pure", "pure_p",         "physical"),
    Axis(589, "homogeneity",        "heterogeneous", "mixed_h",       "homogeneous_p",  "physical"),
    Axis(590, "isotopic",           "depleted_iso",  "natural_iso",   "enriched_iso",   "physical"),
    Axis(591, "molecular_size",     "atomic_p",      "molecular_p",   "macromolecular", "physical"),
    Axis(592, "ionic_covalent",     "ionic_b",       "polar_b",       "covalent_b",     "physical"),
    Axis(593, "acid_base",          "acidic",        "neutral_pH",    "basic_p",        "physical"),
    Axis(594, "oxidation_state",    "reduced",       "neutral_redox", "oxidized",       "physical"),
    Axis(595, "reactivity",         "inert",         "moderate_react","reactive_p",     "physical"),
    Axis(596, "stability_chem",     "unstable_c",    "metastable_c",  "stable_c",       "physical"),
    Axis(597, "solubility",         "insoluble",     "partially_sol", "soluble_p",      "physical"),
    Axis(598, "viscosity",          "low_visc",      "moderate_visc", "high_visc",      "physical"),
    Axis(599, "density_phys",       "low_density_p", "average_dens",  "high_density_p", "physical"),
    Axis(600, "conductivity",       "insulator",     "semiconductor", "conductor",      "physical"),
    Axis(601, "magnetism",          "diamagnetic",   "paramagnetic",  "ferromagnetic",  "physical"),
    Axis(602, "elasticity",         "rigid_p",       "elastic_p",     "plastic_p",      "physical"),
    Axis(603, "ductility",          "brittle",       "moderate_duct", "ductile",        "physical"),
    Axis(604, "hardness",           "soft_h",        "moderate_h",    "hard_h",         "physical"),
    Axis(605, "tensile_compress",   "compressive",   "balanced_tc",   "tensile",        "physical"),
    Axis(606, "biological_class",   "abiotic",       "borderline_bio","biotic",         "physical"),
    Axis(607, "living_dead",        "dead_b",        "dormant",       "living_b",       "physical"),
    Axis(608, "organism_kingdom",   "microbial",     "plant_k",       "animal_k",       "physical"),
    Axis(609, "vertebrate_inv",     "invertebrate",  "boundary_v",    "vertebrate",     "physical"),
    Axis(610, "warm_cold_blood",    "ectothermic",   "mesothermic",   "endothermic",    "physical"),
    Axis(611, "predator_prey",      "prey",          "omnivore",      "predator",       "physical"),
    Axis(612, "carnivore_herbivore","herbivore",     "omnivore_h",    "carnivore",      "physical"),
    Axis(613, "aquatic_terrestrial","aquatic",       "amphibian_pos", "terrestrial",    "physical"),
    Axis(614, "wild_domesticated",  "wild_p",        "feral",         "domesticated",   "physical"),
    Axis(615, "endangered_thriving","endangered",    "stable_pop",    "thriving",       "physical"),
    Axis(616, "young_old_bio",      "young_b",       "mature_b",      "old_b",          "physical"),
    Axis(617, "healthy_sick",       "sick_b",        "convalescent",  "healthy_b",      "physical"),
    Axis(618, "cellular_class",     "prokaryote",    "single_eukar",  "multicellular",  "physical"),
    Axis(619, "metabolic_rate",     "low_metab",     "average_metab", "high_metab",     "physical"),
    Axis(620, "respiration",        "anaerobic",     "facultative",   "aerobic",        "physical"),
    Axis(621, "reproduction_class", "asexual",       "fission",       "sexual",         "physical"),
    Axis(622, "embryonic_adult",    "embryonic",     "juvenile",      "adult_b",        "physical"),
    Axis(623, "ecosystem_role",     "decomposer",    "consumer_b",    "producer_b",     "physical"),
    Axis(624, "tropic_level",       "primary_tl",    "secondary_tl",  "apex_tl",        "physical"),
    Axis(625, "symbiosis",          "parasitic",     "commensal",     "mutualistic",    "physical"),
    Axis(626, "extinct_extant",     "extinct",       "endangered_b",  "extant",         "physical"),
    Axis(627, "fossil_living",      "fossil",        "subfossil",     "living_p",       "physical"),
    Axis(628, "macro_micro",        "subatomic",     "molecular_m",   "macro_p",        "physical"),
    Axis(629, "natural_synthetic",  "natural_p",     "modified_n",    "synthetic_p",    "physical"),
    Axis(630, "organic_inorganic",  "inorganic",     "organometallic","organic_p",      "physical"),
    Axis(631, "renewable",          "non_renewable", "slowly_renew",  "renewable",      "physical"),
]

# ============================================================
# ABSTRACT-DOMAIN LAYER (trits 632-681, 50 axes)
# Mathematics, ethics, epistemology, philosophy.
# ============================================================
ABSTRACT_AXES = [
    Axis(632, "math_pure_applied",  "applied_m",     "computational", "pure_m",         "abstract"),
    Axis(633, "discrete_math_cont", "discrete_m",    "topological",   "continuous_m",   "abstract"),
    Axis(634, "algebra_geometry",   "geometric",     "algebro_geo",   "algebraic",      "abstract"),
    Axis(635, "analysis_combin",    "combinatorial", "discrete_a",    "analytic",       "abstract"),
    Axis(636, "deterministic_chaos","deterministic_a","complex_a",    "chaotic",        "abstract"),
    Axis(637, "linear_nonlinear",   "nonlinear_a",   "weakly_lin",    "linear_a",       "abstract"),
    Axis(638, "exact_numerical",    "numerical_a",   "approximate_a", "exact_a",        "abstract"),
    Axis(639, "structural_proc",    "procedural_a",  "mixed_p",       "structural_a",   "abstract"),
    Axis(640, "constructive_destr", "destructive_a", "neutral_cd",    "constructive_a", "abstract"),
    Axis(641, "ethical_neutral",    "unethical",     "amoral_a",      "ethical",        "abstract"),
    Axis(642, "good_evil",          "evil_a",        "ambiguous_ge",  "good_a",         "abstract"),
    Axis(643, "right_wrong",        "wrong_a",       "ambiguous_rw",  "right_a",        "abstract"),
    Axis(644, "deont_consequent",   "deontological", "virtue_ethics", "consequentialist","abstract"),
    Axis(645, "absolute_relative",  "absolute_e",    "moderate_e",    "relative_e",     "abstract"),
    Axis(646, "moral_aesth",        "aesthetic_value","mixed_value",  "moral_value",    "abstract"),
    Axis(647, "duty_freedom",       "duty_a",        "balanced_df",   "freedom_a",      "abstract"),
    Axis(648, "responsibility",     "irresponsible", "shared_resp",   "responsible",    "abstract"),
    Axis(649, "autonomy",           "constrained_a", "moderately_aut","autonomous_a",   "abstract"),
    Axis(650, "consent",            "coerced",       "implicit_cons", "explicit_cons",  "abstract"),
    Axis(651, "truth_lie",          "false_t",       "uncertain_t",   "true_t",         "abstract"),
    Axis(652, "honest_deceptive",   "deceptive",     "ambiguous_h",   "honest",         "abstract"),
    Axis(653, "transparent_opaque", "opaque_a",      "translucent_a", "transparent_aa", "abstract"),
    Axis(654, "knowledge_ignorance","ignorant_a",    "partial_know",  "knowing_a",      "abstract"),
    Axis(655, "objective_subj",     "subjective",    "intersubj",     "objective_a",    "abstract"),
    Axis(656, "realist_idealist",   "idealist",      "phenomenal",    "realist",        "abstract"),
    Axis(657, "materialist_dual",   "dualist",       "hylomorphic",   "materialist",    "abstract"),
    Axis(658, "monism_pluralism",   "pluralist",     "dualist_m",     "monist",         "abstract"),
    Axis(659, "essentialism",       "constructivist","contextualist", "essentialist",   "abstract"),
    Axis(660, "universalism",       "particularist", "contextualist_u","universalist",  "abstract"),
    Axis(661, "rationalism",        "empiricist",    "pragmatist_r",  "rationalist",    "abstract"),
    Axis(662, "empiricism",         "rationalist_e", "pragmatist_e",  "empiricist_a",   "abstract"),
    Axis(663, "skepticism",         "dogmatic_s",    "fallibilist",   "skeptical_a",    "abstract"),
    Axis(664, "dogmatic_open",      "dogmatic_a",    "moderate_dog",  "open_a",         "abstract"),
    Axis(665, "fideism_reason",     "reason_only",   "moderate_fid",  "fideism",        "abstract"),
    Axis(666, "secular_religious",  "religious_a",   "spiritual_a",   "secular_a",      "abstract"),
    Axis(667, "theism_atheism",     "atheist_a",     "agnostic_a",    "theist_a",       "abstract"),
    Axis(668, "naturalism",         "supernatural",  "neutral_nat",   "naturalist",     "abstract"),
    Axis(669, "physicalism",        "non_physical",  "weakly_phys",   "physicalist",    "abstract"),
    Axis(670, "free_will",          "determinist_f", "compatibilist", "libertarian_f",  "abstract"),
    Axis(671, "determinism_phil",   "indeterminist", "weakly_det",    "determinist_p",  "abstract"),
    Axis(672, "individual_collect", "collective_a",  "balanced_ic",   "individualist_a","abstract"),
    Axis(673, "liberty_security",   "security_a",    "balanced_ls",   "liberty_a",      "abstract"),
    Axis(674, "equality_freedom",   "freedom_pol",   "balanced_ef",   "equality_pol",   "abstract"),
    Axis(675, "tradition_progress", "progressive_a", "moderate_tp",   "traditional_a",  "abstract"),
    Axis(676, "conservative_liberal","liberal_a",    "moderate_cl",   "conservative_a", "abstract"),
    Axis(677, "left_right_pol",     "right_p",       "center_p",      "left_p",         "abstract"),
    Axis(678, "authoritarian_lib",  "libertarian_p", "moderate_al",   "authoritarian",  "abstract"),
    Axis(679, "anarchy_order",      "anarchic",      "moderate_ao",   "ordered_p",      "abstract"),
    Axis(680, "utopian_dystopian",  "dystopian",     "neutral_ud",    "utopian",        "abstract"),
    Axis(681, "optimism_pess",      "pessimistic_a", "realistic_a",   "optimistic_a",   "abstract"),
]

# ============================================================
# CULTURAL / CONTEXTUAL LAYER (trits 682-721, 40 axes)
# Cultural specifics, contexts, conventions.
# ============================================================
CULTURAL_AXES = [
    Axis(682, "western_eastern",    "eastern_c",     "global_c",      "western_c",      "cultural"),
    Axis(683, "global_local",       "local_c",       "regional_c",    "global_c2",      "cultural"),
    Axis(684, "indigenous_imp",     "imported_c",    "creolized",     "indigenous_c",   "cultural"),
    Axis(685, "rural_urban_c",      "rural_c",       "suburban_c",    "urban_c",        "cultural"),
    Axis(686, "high_low_culture",   "popular_c",     "vernacular_c",  "high_c",         "cultural"),
    Axis(687, "elite_mass",         "mass_c",        "middlebrow",    "elite_c",        "cultural"),
    Axis(688, "subculture",         "mainstream_c",  "scene_c",       "subculture_c",   "cultural"),
    Axis(689, "counterculture",     "establishment", "alternative_c", "counter_c",      "cultural"),
    Axis(690, "youth_age",          "young_c",       "midlife_c",     "elder_c",        "cultural"),
    Axis(691, "gender_class",       "feminine_c",    "androgynous_c", "masculine_c",    "cultural"),
    Axis(692, "queer_normative",    "normative_c",   "questioning_c", "queer_c",        "cultural"),
    Axis(693, "religious_sec_c",    "secular_c",     "spiritual_c",   "religious_c",    "cultural"),
    Axis(694, "denomination",       "non_denom",     "ecumenical",    "denominational", "cultural"),
    Axis(695, "ritual_routine",     "routine_c",     "ceremonial",    "ritual_c",       "cultural"),
    Axis(696, "festival_ord",       "ordinary_c",    "celebratory",   "festival_c",     "cultural"),
    Axis(697, "private_public_c",   "private_c",     "communal_c",    "public_c",       "cultural"),
    Axis(698, "family_individual",  "individual_c",  "kinship_c",     "family_c",       "cultural"),
    Axis(699, "ancestor_descend",   "descendant_c",  "self_c",        "ancestor_c",     "cultural"),
    Axis(700, "elder_youth_resp",   "youth_focus",   "balanced_ey",   "elder_focus",    "cultural"),
    Axis(701, "honor_shame",        "shame_c",       "ambiguous_hs",  "honor_c",        "cultural"),
    Axis(702, "guilt_dignity",      "dignity_c",     "balanced_gd",   "guilt_c",        "cultural"),
    Axis(703, "individualism_c",    "collectivist_c","group_oriented","individualist_c","cultural"),
    Axis(704, "high_low_context",   "low_context",   "moderate_ctx",  "high_context",   "cultural"),
    Axis(705, "monochronic",        "polychronic",   "flexible_time", "monochronic_c",  "cultural"),
    Axis(706, "polychronic",        "monochronic_p", "flexible_p",    "polychronic_r",  "cultural"),
    Axis(707, "uncertainty_avoid",  "low_ua",        "moderate_ua",   "high_ua",        "cultural"),
    Axis(708, "power_distance",     "low_pd",        "moderate_pd",   "high_pd",        "cultural"),
    Axis(709, "long_short_term_c",  "short_term_c",  "balanced_lst",  "long_term_c",    "cultural"),
    Axis(710, "indulgence",         "restraint",     "moderate_ind_c","indulgence_c",   "cultural"),
    Axis(711, "achievement",        "ascription",    "balanced_aa",   "achievement_c",  "cultural"),
    Axis(712, "specific_diffuse",   "diffuse_c",     "moderate_sd",   "specific_c",     "cultural"),
    Axis(713, "neutral_emotive",    "neutral_e_c",   "moderate_em",   "emotive_c",      "cultural"),
    Axis(714, "universalism_part",  "particularist_c","contextual_u_c","universalist_c","cultural"),
    Axis(715, "external_internal_c","internal_c2",   "balanced_ei",   "external_c2",    "cultural"),
    Axis(716, "synchronous_seq_c",  "sequential_c",  "balanced_ss",   "synchronous_c",  "cultural"),
    Axis(717, "art_craft_c",        "craft_c",       "applied_a_c",   "fine_art_c",     "cultural"),
    Axis(718, "highbrow_lowbrow",   "lowbrow_c",     "middlebrow_c",  "highbrow_c",     "cultural"),
    Axis(719, "canonical_c",        "non_canon",     "marginal",      "canonical_c2",   "cultural"),
    Axis(720, "official_unofficial","unofficial_c",  "informal_c",    "official_c",     "cultural"),
    Axis(721, "lingua_vernacular",  "vernacular_c",  "creole",        "lingua_franca",  "cultural"),
]

# ============================================================
# ACTION / CAUSAL LAYER (trits 722-768, 47 axes)
# Verbs, transformations, causation, agency.
# ============================================================
ACTION_AXES = [
    Axis(722, "agentive",           "patient_a",     "experiencer_a", "agent_a",        "action"),
    Axis(723, "volitional",         "involuntary",   "ambiguous_v",   "volitional_v",   "action"),
    Axis(724, "intentional_act",    "accidental",    "habitual_act",  "intentional_act","action"),
    Axis(725, "deliberate_imp",     "impulsive",     "automatic",     "deliberate",     "action"),
    Axis(726, "active_passive",     "passive_act",   "middle_voice",  "active_act",     "action"),
    Axis(727, "creative_destruct",  "destructive",   "neutral_cd_a",  "creative_act",   "action"),
    Axis(728, "build_dismantle",    "dismantle",     "modify",        "build_a",        "action"),
    Axis(729, "increase_decrease",  "decrease_a",    "stable_a",      "increase_a",     "action"),
    Axis(730, "begin_end",          "end_act",       "continue",      "begin_act",      "action"),
    Axis(731, "start_stop",         "stop_a",        "pause",         "start_a",        "action"),
    Axis(732, "open_close",         "close_a",       "transitional_oc","open_act",      "action"),
    Axis(733, "give_take",          "take_a",        "exchange",      "give_a",         "action"),
    Axis(734, "send_receive",       "receive_a",     "transit_a",     "send_a",         "action"),
    Axis(735, "go_come",            "come_a",        "stay_a",        "go_a",           "action"),
    Axis(736, "approach_retreat",   "retreat_a",     "stationary_a",  "approach_a",     "action"),
    Axis(737, "advance_recede",     "recede_a",      "stable_pos",    "advance_a",      "action"),
    Axis(738, "rise_descend",       "descend_a",     "level_a",       "rise_a",         "action"),
    Axis(739, "expand_contract_a",  "contract_a",    "stable_size_a", "expand_a",       "action"),
    Axis(740, "speak_listen",       "listen_a",      "silent_a_act",  "speak_a",        "action"),
    Axis(741, "ask_answer",         "answer_a",      "neutral_q",     "ask_a",          "action"),
    Axis(742, "accept_reject",      "reject_a",      "consider",      "accept_a",       "action"),
    Axis(743, "approve_deny",       "deny_a",        "review_a",      "approve_a",      "action"),
    Axis(744, "permit_forbid",      "forbid_a",      "tolerate",      "permit_a",       "action"),
    Axis(745, "command_request",    "request_a",     "suggest_a",     "command_a",      "action"),
    Axis(746, "lead_follow",        "follow_a",      "co_lead",       "lead_a",         "action"),
    Axis(747, "teach_learn",        "learn_a",       "discuss_a",     "teach_a",        "action"),
    Axis(748, "help_hinder",        "hinder_a",      "neutral_help",  "help_a",         "action"),
    Axis(749, "support_oppose",     "oppose_a",      "abstain",       "support_a",      "action"),
    Axis(750, "attack_defend",      "defend_a",      "neutral_ad",    "attack_a",       "action"),
    Axis(751, "win_lose",           "lose_a",        "draw_a",        "win_a",          "action"),
    Axis(752, "succeed_fail",       "fail_a",        "partial_succ",  "succeed_a",      "action"),
    Axis(753, "complete_abort",     "abort_a",       "pause_act",     "complete_a",     "action"),
    Axis(754, "cause_effect",       "effect_a",      "mediator",      "cause_a",        "action"),
    Axis(755, "prevent_enable",     "prevent_a",     "neutral_pe",    "enable_a",       "action"),
    Axis(756, "necessary_caus",     "sufficient_c",  "contributory",  "necessary_c2",   "action"),
    Axis(757, "direct_indirect_c",  "indirect_c",    "mediated_c",    "direct_c",       "action"),
    Axis(758, "proximal_distal_c",  "distal_c",      "intermediate_c","proximal_c",     "action"),
    Axis(759, "single_cumulative",  "cumulative_c",  "intermediate_sc","single_c2",     "action"),
    Axis(760, "linear_emergent_c",  "emergent_c",    "complex_c2",    "linear_c2",      "action"),
    Axis(761, "force_strength",     "weak_force_a",  "moderate_force","strong_force_a", "action"),
    Axis(762, "violence_peaceful",  "peaceful_a",    "tense_a",       "violent_a",      "action"),
    Axis(763, "constructive_aggr",  "destructive_a", "neutral_aggr",  "constructive_a2","action"),
    Axis(764, "voluntary_forced",   "forced_a",      "coerced_a",     "voluntary_a",    "action"),
    Axis(765, "irrevocable_rev",    "reversible_a",  "partly_rev",    "irrevocable_a",  "action"),
    Axis(766, "spontaneous_planned","planned_a",     "improvised",    "spontaneous_a",  "action"),
    Axis(767, "ritual_random_act",  "random_a",      "patterned_a",   "ritual_a",       "action"),
    Axis(768, "completion_state",   "incomplete_a",  "in_progress_a", "complete_act",   "action"),
]

# ============================================================
# Assemble all 768 axes
# ============================================================

NEW_AXES: List[Axis] = (
    LINGUISTIC_AXES
    + COGNITIVE_AXES
    + AFFECTIVE_AXES
    + SOCIAL_AXES
    + SPATIAL_AXES
    + TEMPORAL_FINE_AXES
    + QUANTITATIVE_AXES
    + LOGICAL_AXES
    + AESTHETIC_AXES
    + PHYSICAL_AXES
    + ABSTRACT_AXES
    + CULTURAL_AXES
    + ACTION_AXES
)

ALL_AXES_768: List[Axis] = list(_BASE_81) + NEW_AXES

# Index by ID
AXIS_BY_ID_768: Dict[int, Axis] = {a.id: a for a in ALL_AXES_768}

# Group by layer
AXES_BY_LAYER_768: Dict[str, List[Axis]] = {}
for ax in ALL_AXES_768:
    AXES_BY_LAYER_768.setdefault(ax.layer, []).append(ax)


def assert_complete():
    """Sanity check: 768 axes, ids 1..768, all populated."""
    assert len(ALL_AXES_768) == 768, f"Expected 768 axes, got {len(ALL_AXES_768)}"
    ids = sorted(a.id for a in ALL_AXES_768)
    assert ids == list(range(1, 769)), "Axis IDs are not 1..768 contiguous"
    for a in ALL_AXES_768:
        assert a.name and a.negative and a.positive and a.layer, f"Empty fields in axis {a.id}"
    return True


if __name__ == "__main__":
    assert_complete()
    print(f"768-axis grounding: {len(ALL_AXES_768)} axes across "
          f"{len(AXES_BY_LAYER_768)} layers")
    for layer, axes in AXES_BY_LAYER_768.items():
        print(f"  {layer}: {len(axes)} axes (trits {axes[0].id}-{axes[-1].id})")
